os:
- linux
services:
- docker
language: node_js
node_js:
- 10.14.1
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.m2"
env:
  global:
  - NODE_VERSION=10.14.1
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
  - JHI_DISABLE_WEBPACK_LOGS=true
  - secure: cH2QlqMJ77qLgjT/A1S3Y6OVmf1fnFERpUZSqusjvRDXod7/LEMo2rWPDFIacsgc2UtnydXGTbq4xLBQX0m7KGBC1XXcs2UIkNd7dFwgmnnU1ZU86KLhz+8pKQ1PHauKTYs3fq3jKMWUGp2sBo2kII/zXynPEb2Q5/rB0OMbEDyVD2jepCMNA+lTKqfPgPuV1Z+Z8hPuaKXh1rXF39chDLXfbRP5J8RWP1W1sbnN9RcHHAKaQc320rmq6jDXK4muQa4CrtZgwC4QN+KCIFsxs9+LV/B+ybj90DXpXt4twCVQ8oDIxyQUgWL8heJDxNWRBADgbxgXFi8gZ48D/nD9XIfYRU7WBG6c56M12hvmT2lDgIAKXeOPkjX1hwbP+YonRTzwPASNfB3ogt5y1/XX1LDceqGeExlwrAx1US7ODO3zgCmtQJaVMYvBBYjRj6V965BXKjwI3v4gWeZQ7LZNq4qdDpvxvd6MQ9/RkqfbQgiAy1ty/jd/rupSx0PuDnRE9UOYw7pFjsqS4iPNqxNtbkbtaADizP/Qz7M3mDn64WRenr7oxpCWrOU95b85eHcZJbw4E13WueG38hg/T2HnTk1f0C9HdYQmurca4BZV9o+P0mJkGqyvm+mkZw5EQbAVwD8fgzYUpMX/1WBOWrquiB/8xneOUER0luXYJiuA6N8=
  - secure: i34v0Bm9+/rqoY2AxQvO82uVFeXQ8XREv0O9XQQntsjCTEMFh/aVIDkpHrBi09ESo2xmxdexyKdQ9zxHsE0Urs/aFZTcPNbI5+l8YFMSxim3R+VtQPmF+E+maYCtng92y8wL81y+BK6A4w40jRbAPPO+xHoElhgV+7y7s7jDW4lzFFG3KZgxrBTKRSdJj2QMyS3HvxaZPtqOeonXgh+XBg4vUA+3uV7yy+VZgv94SMV22oA9tLMDncbXb/6w/nQNfyOVFv0ZCuBtMZQ5QazFO7mcb/ceWY/THcdXfM7AU3/vcVx/NyX6Lgl4r/QUHszW2oFdKx8PxnKeWv9poK2VuPcJ0bTNCSNMrWTBkviStdQBPt59AT1h7HYd856QKd8Inu3zQEbLJ3IddoacZbkacUw7OrhFewOUB9XmkHGdmnMGQc0y6IuNdC57zFew/8OnytFjd6iO6BmJv1ngJPf+e9VAunirVJFqJ1A7EW+qC5eURERzJl2l3/K42itEdoSqV9a35SuLFG3oWVhI+mC/9+OBtGMJwaAvyllmSpxUR6Udvm/7ny5xL3bGmNRKyLun5SCdnjO4SZ/jVEYFTYSYEOBVYPq9Sk3zWw+OvkbYEsHr7ymWwXFGVMV/agQCqjrcHLfbYmu07in0ntoOZol8LweJUkRqrB/8+a/QFwxSLOQ=
  - secure: tC6IhoIH97wgu4OYMuytLP8xeG+jexQlORs8qfAAfsfnAzOtVBvhYcjgwlJSoN7DZjXZYWXhpWUUW2EsILPqvRFLwg8dL5DwoC6yWW2IIxlc4w2hwDePJEzK5o58c3L4BOU00c/+3xN1ss8kUIXoqT3pG/lo9hY90jNPyYe6vHCuK9UCRiElfRc8z6xv2Te0kdtWCIUHI3OveMqt0lb+5tDvJr54eT27Pv1RVCFeSSRJL0HI9KLN4/xjX4lbNssKlNE+1uSX5AJtzPrq3BDMdgtJzlYxWFovBFz/LUAdCFMsdvYD7j0kHIQmrpTiFfzXYiy1/r4wn80ryHZqoiL+dAUfWfCv1OYvVsfgaWKbTvV0LD+5YTKZSrrFnwfYIwUXO3exsVk+WteC9gWQLyHsLGW+xMaKj/t+YYKVD0c4XR78iSEPysW19Lk/myK5jMk/7WB2V9uKC0btN9mRuc9YawhD6CzPLdtE3C1B4UIC0aHIg9iu4wD9Yj/FjxNOnhSeaj2ZgglS8gMeWn74RonpgYS0NLOXnnsulg6+ek+eWAIHkSwoaozadZrbhWHjAQ2x+/+6E9ptBnLnFrmnqBSvS2PBNVWYvv08cjusXkvdnM1IWxlUsZ0SmrEDvf0drhIaB7U2/bnhWH3o861f/e9hViRNyI9JJMBhMgXnjdFAmZA=
before_install:
- jdk_switcher use oraclejdk8
- java -version
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- nvm install $NODE_VERSION
- npm install -g npm
- node -v
- npm -v
install:
- npm install
script:
- chmod +x mvnw
- "./mvnw clean test"
- "./mvnw verify -Pprod -DskipTests"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
